@startuml
left to right direction
title "C5. Usuário cadastra sua empresa"

User as "Usuário Comum"

rectangle "USUÁRIO AUTENTICADO" {
    (Cadastrar Empresa) as CadEmpresa
    (Dashboard) as Dashboard
}

(Login) as Login

User -r--> Login
Login --> Dashboard
Dashboard --> CadEmpresa
@enduml