@startuml
left to right direction
title "C6. Usuário edita os dados sua empresa"

User as "Usuário Comum"

rectangle "USUÁRIO AUTENTICADO" {
    (Editar dados da Empresa) as FavEmpresa
    (Dashboard) as VerEmpresas
}

(Login) as Login

User -r--> Login
Login --> VerEmpresas
VerEmpresas --> FavEmpresa
@enduml