@startuml
left to right direction
title "C9. Usuário remove um favorito."

User as "Usuário Comum"

rectangle "USUÁRIO AUTENTICADO" {
    (Favoritos) as favoritos
    (Dashboard) as VerEmpresas
    (Remover Favorito) as remove
}

(Login) as Login

User -r--> Login
Login --> VerEmpresas
VerEmpresas -r--> favoritos
favoritos --> remove
@enduml