@startuml
left to right direction
title "C4. Usuário adiciona uma empresa aos Favoritos"

User as "Usuário Comum"

rectangle "USUÁRIO AUTENTICADO" {
    (Adicionar Empresa aos Favoritos) as FavEmpresa
}

(Ver Empresas) as VerEmpresas
(Login) as Login

User -r--> Login
Login --> VerEmpresas
VerEmpresas --> FavEmpresa
@enduml