@startuml
left to right direction
title "C2. Usuário se autentica no sistema"
User as "Usuário Comum"

rectangle "USUÁRIO AUTENTICADO" {
    (Dashboard) as Dashboard
}

(Login) as Login

User --> Login
Login --> Dashboard

@enduml