@startuml
left to right direction
title "UC8. Usuário edita os seus dados de perfil."
scale 2

User as "Usuário Comum"

rectangle "USUÁRIO AUTENTICADO" {
    (Editar dados do perfil) as FavEmpresa
    (Dashboard) as VerEmpresas
}

(Login) as Login

User -r--> Login
Login --> VerEmpresas
VerEmpresas --> FavEmpresa
@enduml