@startuml
left to right direction
title "AC6. Administrador exclui um Perfil de Acesso"
Admin as "Administrador do Sistema"
scale 2

rectangle "PAINEL DE CONTROLE ADMIN" {
    (Perfis de Acesso) as roles
    (Excluir Perfil de Acesso) as delete
}

(Login) as login

Admin -r--> login
login -d--> roles
roles --> delete
@enduml