@startuml
left to right direction
scale 2

Admin as "Administrador do Sistema"

rectangle "PAINEL DE CONTROLE ADMIN" {
    (Gerenciar Empresas) as GerEmpresas
    (Gerenciar Estados) as GerEstados
    (Gerenciar Cidades) as GerCidades
    (Gerenciar Categorias) as GerCategorias
    (Gerenciar Usuários) as GerUsuarios
    (Ver Estatísticas) as VerEstatisticas
}

(Login) as Login
(Ver Empresas) as VerEmpresas
(Favoritar Empresa) as FavEmpresa

Admin --> Login
Admin --> VerEmpresas
Login --> GerEmpresas
Login --> GerEstados
Login --> GerCidades
Login --> GerCategorias
Login --> GerUsuarios
Login --> FavEmpresa
Login --> VerEstatisticas

@enduml